# https://gitlab.jatic.net/groups/jatic/ibm/-/wikis/HEART-Conda-Information

name: heart-conda-dev 
channels:
  - conda-forge
dependencies:
  # Optional Dependencies
  - datasets>=2.18.0
  - jupyter>=1.1.1
  - matplotlib>=3.9
  - multiprocess>=0.70.16
  - numba>=0.60.0
  - pandas>=2.2.2
  - pillow>=10.4.0
  - pycocotools>=2.0.8
  - timm>=1.0.9
  - transformers>=4.44.2
  - torchmetrics>=1.4.2
  - pympler>=1.1
  - gputil>=1.4.0
  - pytorch>=2.1.1,<=2.3.1
  - torchvision<0.19
  # Yolov5 cannot support huggingface_hub>=0.25.0
  - huggingface_hub<0.25.0
  # Dev
  - isort>=5
  - pytest>=8.3
  - pytest-cov>=4.1
  # Pip Overrides (Fixes known issues or unavailable via conda-forge)
  - pip
  - pip:
    # Missing osx-arm64 artifacts via conda-forge
    - kornia>=0.7.3
    # Unavailable via conda-forge
    - opencv-python>=4.10.0.84
    - memory-profiler>=0.61.0
    # Yolov5 does not support python 3.9 due to AWS-CLI dependencies (boto3/botocore/urllib3)
    # See https://github.com/fcakyon/yolov5-pip/discussions/256 for more information
    - yolov5>=7.0.13
