# https://gitlab.jatic.net/groups/jatic/ibm/-/wikis/HEART-Conda-Information

name: heart-conda-dev 
channels:
  - conda-forge
dependencies:
# HEART Required Dependencies
# This is the set of install_requires dependencies defined in pyproject.toml
- adversarial-robustness-toolbox >=1.19.1
- datasets >=3.2.0
- maite >=0.7.0
- multiprocess >=0.70.0
- numpy >=1.18.5, <2
- pillow >=11.0.0
- scikit-learn >=0.22.2
- six >=1.0.0
- setuptools >=78.1.1
- tqdm >=4.0.0
- transformers >=4.0.0, <4.49.0

# HEART Minimal Optional Dependencies
# This is the complete set of optional dependencies necessary for unit testing
- timm >=1
- pytorch >2.3.1
- torchmetrics >=1
- torchvision >=0.18.0
- pycocotools >=2

# HEART Dev Dependencies
# This is the complete set of dev dependencies necessary for unit testing
- pip >=25.0.1
- psutil >=7.0.0
- pytest >=8
- pytest-mock >=3
- pytest-cov >=6

# Yolov5 Compatibility
# Note: Yolov5 must be installed manually as it does not support Python <= 3.9
- huggingface_hub <0.25.0
