# https://gitlab.jatic.net/groups/jatic/ibm/-/wikis/HEART-Conda-Information

package:
  name: "heart-library"
  version: {{ PYPROJECT_VERSION }}

source:
  url: dist/heart_library-{{ PYPROJECT_VERSION }}.tar.gz

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<3.12
    - poetry-core
    - pip
  run:
    - python >=3.9,<3.12
    - adversarial-robustness-toolbox >=1.19.1
    - datasets >=3.2.0
    - maite >=0.7.0
    - multiprocess >=0.70.0
    - numpy >=1.18.5,<2
    - pillow >=11.0.0
    - scikit-learn >=0.22.2
    - six >=1.0.0
    - setuptools >=75
    - tqdm >=4.0.0
    - transformers >=4.44.2,<4.49.0

test:
  imports:
    - heart_library
  commands:
    - pip check
  requires:
    - pip

about:
  license: MIT
  license_file: LICENSE.txt
